'use client';

import React from 'react';
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerDescription,
  DrawerFooter,
  DrawerClose,
} from '@/components/ui/drawer';
import { Button } from '@/components/ui/button';
import { useUiStore } from '@/lib/store/ui';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell } from 'recharts';
import { CheckCircle, ShieldCheck, Sparkles } from 'lucide-react';

export function ReasoningDrawer() {
  const openDrawer = useUiStore((s) => s.openDrawer);
  const payload = useUiStore((s) => s.drawerPayload) as {
    candidateName?: string;
    score?: number;
    reason?: string;
    breakdown?: {
      skillMatch: number;
      workload: number;
      slaSafety: number;
      performance: number;
      location: number;
    };
  } | undefined;
  const closeDrawer = useUiStore((s) => s.closeDrawer);

  const isOpen = openDrawer === 'reasoning';

  const candidateName = payload?.candidateName || 'Vikram Malhotra';
  const score = payload?.score ?? 92;
  const reason =
    payload?.reason ||
    'Best skill match (Stripe Expert, Node.js Expert), low current workload (30%), and zero SLA risk on existing commitments.';

  const breakdown = payload?.breakdown || {
    skillMatch: 95,
    workload: 90,
    slaSafety: 98,
    performance: 92,
    location: 85,
  };

  const chartData = [
    { factor: 'Skill Match', value: breakdown.skillMatch, color: '#3b82f6' },
    { factor: 'Workload Headroom', value: breakdown.workload, color: '#10b981' },
    { factor: 'SLA Safety', value: breakdown.slaSafety, color: '#6366f1' },
    { factor: 'Historical Perf', value: breakdown.performance, color: '#f59e0b' },
    { factor: 'Location/TZ', value: breakdown.location, color: '#8b5cf6' },
  ];

  return (
    <Drawer open={isOpen} onOpenChange={(open) => !open && closeDrawer()}>
      <DrawerContent className="max-w-xl">
        <DrawerHeader>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1 rounded bg-primary/10 text-primary text-xs font-semibold flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> AI Decision Explainability
            </span>
          </div>
          <DrawerTitle className="text-xl font-bold flex items-center justify-between">
            <span>{candidateName}</span>
            <span className="text-lg font-mono font-bold text-emerald-600 bg-emerald-50 dark:bg-emerald-950/40 px-3 py-0.5 rounded-full border border-emerald-200">
              {score} / 100
            </span>
          </DrawerTitle>
          <DrawerDescription>
            Multi-factor scoring breakdown generated by autonomous allocation agent.
          </DrawerDescription>
        </DrawerHeader>

        <div className="p-4 space-y-5 overflow-y-auto max-h-[70vh]">
          {/* Executive rationale */}
          <div className="p-4 rounded-lg bg-muted/40 border space-y-1.5">
            <h4 className="text-xs font-semibold uppercase text-muted-foreground">Allocation Rationale</h4>
            <p className="text-sm font-medium leading-relaxed text-foreground">{reason}</p>
          </div>

          {/* Factor Breakdown Chart */}
          <div className="space-y-2">
            <h4 className="text-xs font-semibold uppercase text-muted-foreground">Decision Factor Matrix</h4>
            <div className="h-56 w-full pt-2">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                  <XAxis type="number" domain={[0, 100]} tick={{ fontSize: 11 }} />
                  <YAxis type="category" dataKey="factor" tick={{ fontSize: 11 }} width={110} />
                  <Tooltip formatter={(val) => [`${val} / 100`, 'Score']} />
                  <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Detailed metrics table */}
          <div className="border rounded-lg overflow-hidden divide-y divide-border/60 text-xs">
            {chartData.map((d) => (
              <div key={d.factor} className="flex items-center justify-between p-2.5">
                <span className="font-medium text-foreground">{d.factor}</span>
                <span className="font-mono font-bold">{d.value}%</span>
              </div>
            ))}
          </div>
        </div>

        <DrawerFooter className="border-t pt-4">
          <DrawerClose asChild>
            <Button variant="outline">Close Details</Button>
          </DrawerClose>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  );
}
